name: Zip and Upload Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Files
      run: |
        ls -la
        ls -la ./*

    - name: Zip Project Files
      run: |
        zip -r project-files.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: project-artifact
        path: project-files.zip
