name: Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: "mkdir ./DrugDealerSimulatorVortexExtension"
      - run: "mv gameart.jpg ./DrugDealerSimulatorVortexExtension/"
      - run: "mv index.js ./DrugDealerSimulatorVortexExtension/"
      - run: "mv info.json ./DrugDealerSimulatorVortexExtension/"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Download-Me
          path: |
            ./
            !.github
            !.gitignore
            !.git
