name: Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: "mkdir ./zipped"
      - run: "mv gameart.jpg ./zipped"
      - run: "mv index.js ./zipped"
      - run: "mv info.json ./zipped"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Download-Me
          path: |
            ./
            !.github
            !.gitignore
            !.git
