name: "RunZip"
on: [push]
jobs:
  RunZip:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install zip
    - run: pwd
    - run: zip Zip.zip *
    - uses: actions/upload-artifact@v4
      with:
        name: DownloadMe!
        path: /Zip.zip