name: Upload Artifact

on:
  push:
    branches:
      - master # Replace with your branch name

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact # Replace with your desired artifact name
          path: |
            ./
            !.github/ # Exclude the .github directory
            !.gitignore
