name: "RunZip"
on: [push]
jobs:
  RunZip:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install zip
    - run: ls
    - run: zip /home/runner/work/DrugDealerSimulatorVortexSupport/DrugDealerSimulatorVortexSupport/Zip.zip *
    - uses: actions/upload-artifact@v4
      with:
        name: DownloadMe!
        path: /home/runner/work/DrugDealerSimulatorVortexSupport/DrugDealerSimulatorVortexSupport/Zip.zip